[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip MCXN947"
rustflags = [
  "-C", "link-arg=-Map=target/app.map",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
