[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip-description-path ./MCXN.yaml --chip MCXN947VDF"
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Map=app.map",
]

[build]
target = "thumbv8m.main-none-eabi"
